name: Deploy to AtCoder

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: './joi-md-private/requirements.txt'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U -r ./joi-md-private/requirements.txt
      - name: Run a build script
        run: bash ./joi-md-private/build.sh
      - name: Run a deploy script
        run: python3 ./joi-md-private/deploy.py ${{ secrets.USERNAME }} ${{ secrets.REVEL_SESSION }} tasks.yaml
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Auto update HTML by workflow'
          file_pattern: '*/*.html'
          commit_options: '--force'
