name: Deploy to AtCoder

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SSH Setting
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          mkdir -p $HOME/.ssh/
          echo -e "$TOKEN" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
      - name: Checkout submodule
        run: git submodule update --init --force --recursive
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run a build script
        run: bash ./joi-md-private/build.sh
      - name: Run a deploy script
        run: python3 ./joi-md-private/deploy.py ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }} tasks.yaml
